// Vehicle heritage and unique descriptions
// What makes each vehicle special, known for, or historically significant

export const vehicleHeritage: Record<string, string> = {
  // Toyota
  'Toyota Camry': 'America\'s best-selling sedan for over 20 years, renowned for bulletproof reliability and exceptional resale value.',
  'Toyota Corolla': 'The world\'s best-selling car of all time with over 50 million sold, known for unmatched dependability.',
  'Toyota RAV4': 'Pioneer of the compact SUV segment since 1994, now the best-selling non-truck vehicle in America.',
  'Toyota Highlander': 'The gold standard for family SUVs, praised for reliability and strong resale value.',
  'Toyota 4Runner': 'A true body-on-frame SUV built for off-road adventure, beloved by outdoor enthusiasts for decades.',
  'Toyota Tacoma': 'The mid-size truck benchmark, famous for going over 1 million miles and holding its value better than any truck.',
  'Toyota Tundra': 'Toyota\'s full-size truck, built in Texas and known for legendary durability.',
  'Toyota Prius': 'The car that started the hybrid revolution in 1997, synonymous with fuel efficiency.',
  'Toyota Supra': 'Legendary sports car icon, the fifth generation revives the nameplate with BMW partnership.',
  'Toyota GR86': 'Pure driving enthusiast\'s car developed with Subaru, focused on balanced handling over raw power.',
  'Toyota Land Cruiser': 'The ultimate off-road legend with 70+ years of conquering the world\'s toughest terrain.',
  'Toyota Crown': 'Historic nameplate returning to America, blending sedan comfort with crossover practicality.',
  'Toyota Sequoia': 'Full-size SUV with towing prowess and room for the whole family plus gear.',
  'Toyota Venza': 'Stylish crossover exclusive with hybrid power, bridging the gap between RAV4 and Highlander.',
  'Toyota Sienna': 'The only minivan offering all-wheel drive and hybrid-only powertrain.',
  'Toyota bZ4X': 'Toyota\'s first purpose-built electric SUV, marking their entry into the EV era.',
  'Toyota Grand Highlander': 'Extended Highlander with more third-row space and cargo capacity for larger families.',
  
  // Honda
  'Honda Accord': 'Over 40 years of excellence, consistently rated among the best midsize sedans ever made.',
  'Honda Civic': 'Iconic compact that redefined what a small car could be, a favorite for enthusiasts and commuters alike.',
  'Honda CR-V': 'America\'s best-selling SUV for years, setting the standard for compact crossover practicality.',
  'Honda Pilot': 'Three-row family hauler known for car-like handling and Honda reliability.',
  'Honda HR-V': 'Subcompact SUV with class-leading rear seat space thanks to Honda\'s Magic Seat.',
  'Honda Odyssey': 'The minivan enthusiasts choose, famous for innovative features and driving dynamics.',
  'Honda Ridgeline': 'The pickup truck for people who don\'t want a traditional truck, with unibody construction and car-like ride.',
  'Honda Passport': 'Adventure-ready SUV positioned between CR-V and Pilot for those who need more capability.',
  'Honda Civic Type R': 'The ultimate front-wheel-drive performance car, a track weapon in hot hatch clothing.',
  'Honda Prologue': 'Honda\'s electric future built on GM\'s Ultium platform.',
  
  // Ford
  'Ford F-150': 'America\'s best-selling vehicle for 40+ years, the truck that built a nation.',
  'Ford F-150 Lightning': 'The electric revolution comes to America\'s favorite truck, with power to run your home.',
  'Ford Mustang': 'The original pony car since 1964, an American icon that defined affordable performance.',
  'Ford Mustang Mach-E': 'Bold electric SUV that brings Mustang spirit to the EV world.',
  'Ford Bronco': 'Legendary off-roader reborn after 25 years, ready to take on the Jeep Wrangler.',
  'Ford Bronco Sport': 'Compact adventure SUV with legitimate off-road capability and city-friendly size.',
  'Ford Explorer': 'The SUV that started America\'s love affair with sport utilities in 1990.',
  'Ford Expedition': 'Full-size SUV powerhouse for families who need maximum space and towing capacity.',
  'Ford Ranger': 'Mid-size truck returning to glory with modern features and proven capability.',
  'Ford Maverick': 'Revolutionary compact hybrid truck starting under $25,000, redefining value.',
  'Ford Edge': 'Sporty two-row crossover offering more style and performance than typical family haulers.',
  'Ford Escape': 'Compact SUV that helped define the segment, now available as a plug-in hybrid.',
  'Ford Super Duty': 'The heavy-duty work truck trusted by contractors and towers nationwide.',
  
  // Chevrolet  
  'Chevrolet Silverado': 'Bow-tie truck heritage dating back to 1918, rivaling F-150 in capability.',
  'Chevrolet Corvette': 'America\'s sports car since 1953, the C8 generation moved the engine behind the driver for the first time.',
  'Chevrolet Corvette E-Ray': 'The fastest Corvette ever made, combining V8 power with electric AWD for 2.5-second 0-60.',
  'Chevrolet Camaro': 'Muscle car icon and Mustang rival since 1966, a pure performance machine.',
  'Chevrolet Tahoe': 'Full-size SUV workhorse, the Suburban\'s slightly smaller sibling.',
  'Chevrolet Suburban': 'The longest-running nameplate in automotive history, in production since 1935.',
  'Chevrolet Equinox': 'Compact crossover offering great value and now available as an affordable EV.',
  'Chevrolet Traverse': 'Three-row family crossover with one of the largest cargo areas in its class.',
  'Chevrolet Colorado': 'Mid-size truck with available off-road ZR2 trim that rivals dedicated rock crawlers.',
  'Chevrolet Blazer': 'Sporty mid-size SUV reviving a legendary nameplate with modern style.',
  'Chevrolet Trailblazer': 'Subcompact SUV punching above its weight class in features and style.',
  'Chevrolet Bolt EV': 'Affordable long-range EV that helped democratize electric cars.',
  'Chevrolet Bolt EUV': 'Stretched Bolt with more space and available Super Cruise hands-free driving.',
  
  // Tesla
  'Tesla Model 3': 'The car that made EVs mainstream, with over 2 million sold worldwide.',
  'Tesla Model Y': 'The world\'s best-selling vehicle in 2023, combining Model 3 tech with SUV practicality.',
  'Tesla Model S': 'The car that proved EVs could be desirable, with supercar-beating performance.',
  'Tesla Model X': 'Falcon-wing doors and ludicrous acceleration in a family SUV package.',
  'Tesla Cybertruck': 'Polarizing stainless steel pickup that broke the internet and redefined truck design.',
  
  // BMW
  'BMW 3 Series': 'The benchmark sport sedan since 1975, defining the category for nearly 50 years.',
  'BMW 5 Series': 'Executive sedan balancing luxury and driving dynamics better than any rival.',
  'BMW 7 Series': 'Flagship luxury sedan pushing technology boundaries with each generation.',
  'BMW X3': 'Compact luxury SUV that drives like a sport sedan.',
  'BMW X5': 'The original luxury SUV since 1999, still setting the standard for driving dynamics.',
  'BMW X7': 'Full-size luxury SUV with presence and the brand\'s signature driving feel.',
  'BMW M3': 'The iconic performance sedan, track-capable from the factory.',
  'BMW M4': 'Two-door M3 variant continuing BMW\'s motorsport legacy.',
  'BMW M5': 'Super sedan disguised as an executive car, capable of embarrassing supercars.',
  'BMW i4': 'Electric sedan with true BMW driving character and up to 300 miles of range.',
  'BMW iX': 'Flagship electric SUV showcasing BMW\'s sustainable future vision.',
  'BMW i7': 'Electric 7 Series offering silent luxury and cutting-edge technology.',
  'BMW Z4': 'Open-top roadster developed alongside the Toyota Supra.',
  
  // Mercedes-Benz
  'Mercedes-Benz C-Class': 'The entry point to Mercedes luxury, refined and sophisticated.',
  'Mercedes-Benz E-Class': 'The heart of Mercedes-Benz, executive luxury at its finest.',
  'Mercedes-Benz S-Class': 'The best car in the world, setting luxury standards since 1972.',
  'Mercedes-Benz GLC': 'Best-selling Mercedes, combining SUV practicality with the brand\'s luxury.',
  'Mercedes-Benz GLE': 'Mid-size luxury SUV with available third row and plug-in hybrid options.',
  'Mercedes-Benz GLS': 'The S-Class of SUVs, full-size luxury for discerning families.',
  'Mercedes-Benz AMG GT': 'Hand-built performance machine with racing DNA.',
  'Mercedes-Benz EQS': 'The most aerodynamic production car ever made, all-electric S-Class luxury.',
  'Mercedes-Benz EQE': 'Electric E-Class equivalent with impressive range and technology.',
  'Mercedes-Benz G-Class': 'Iconic off-road legend since 1979, the original luxury SUV.',
  
  // Porsche
  'Porsche 911': 'The definitive sports car for 60 years, continuously evolved perfection.',
  'Porsche Taycan': 'Electric sedan proving EVs can deliver true Porsche driving dynamics.',
  'Porsche Cayenne': 'The SUV that saved Porsche, sports car DNA in a practical package.',
  'Porsche Macan': 'Compact performance SUV, the best-handling vehicle in its class.',
  'Porsche Panamera': 'Four-door sports car challenging the definition of sedan.',
  'Porsche 718 Cayman': 'Mid-engine sports car offering 911 driving thrills at a lower price.',
  'Porsche 718 Boxster': 'Open-top roadster for pure driving enjoyment.',
  
  // Exotic/Supercar Brands
  'Ferrari SF90': 'The most powerful Ferrari road car ever, 986 horsepower plug-in hybrid.',
  'Ferrari 296 GTB': 'V6 hybrid supercar delivering Ferrari\'s efficiency future.',
  'Ferrari Roma': 'Elegant grand tourer capturing la dolce vita spirit.',
  'Ferrari Purosangue': 'Ferrari\'s first four-door, breaking tradition with stunning results.',
  'Lamborghini Huracán': 'Naturally aspirated V10 supercar, possibly the last of its kind.',
  'Lamborghini Urus': 'Super SUV that dominates its segment in performance.',
  'Lamborghini Revuelto': 'The first Lamborghini V12 hybrid, 1,001 horsepower of the future.',
  'McLaren 720S': 'Engineering excellence with performance that challenges cars twice its price.',
  'McLaren Artura': 'High-performance hybrid supercar marking McLaren\'s electric future.',
  'McLaren 750S': 'Evolution of the 720S with even more refinement and power.',
  'Aston Martin DB12': 'The world\'s first super tourer, redefining grand touring luxury.',
  'Aston Martin Vantage': 'Entry-level Aston with proper sports car aggression.',
  'Aston Martin DBX': 'Aston\'s SUV bringing British luxury to new customers.',
  'Bentley Continental GT': 'Grand touring perfection, handcrafted British luxury.',
  'Bentley Flying Spur': 'Four-door version of the Continental, ultimate luxury sedan.',
  'Bentley Bentayga': 'The original ultra-luxury SUV, setting standards others follow.',
  'Rolls-Royce Phantom': 'The pinnacle of automotive luxury, nothing else compares.',
  'Rolls-Royce Ghost': 'Entry to Rolls-Royce, if $300k can be called entry-level.',
  'Rolls-Royce Cullinan': 'Rolls-Royce\'s first SUV, named after the largest diamond ever found.',
  'Rolls-Royce Spectre': 'The first electric Rolls-Royce, silent luxury perfected.',
  'Bugatti Chiron': 'The fastest and most expensive production car, 1,500 horsepower of excess.',
  
  // Lexus
  'Lexus ES': 'Quiet luxury sedan known for whisper-quiet cabins and reliability.',
  'Lexus RX': 'The original luxury crossover since 1998, still the best-seller.',
  'Lexus NX': 'Compact luxury SUV with bold styling and hybrid options.',
  'Lexus GX': 'Body-on-frame luxury off-roader for those who actually venture off-road.',
  'Lexus LX': 'The luxury Land Cruiser, capable of going anywhere in supreme comfort.',
  'Lexus IS': 'Sport sedan bringing driving excitement to Lexus.',
  'Lexus LC': 'Stunning grand tourer showcasing Lexus design and craftsmanship.',
  'Lexus LS': 'Flagship sedan that launched the brand in 1989, redefining luxury expectations.',
  'Lexus TX': 'New three-row luxury SUV filling the gap between RX and LX.',
  'Lexus RZ': 'First dedicated Lexus EV, marking the brand\'s electric transition.',
  
  // Jeep
  'Jeep Wrangler': 'The original off-roader since 1941, unchanged in spirit for 80+ years.',
  'Jeep Grand Cherokee': 'Refined SUV that brings luxury to Jeep capability.',
  'Jeep Cherokee': 'Trail-rated capability in a more city-friendly package.',
  'Jeep Gladiator': 'The only convertible pickup truck on the market.',
  'Jeep Compass': 'Affordable way into Jeep ownership with real off-road credentials.',
  'Jeep Grand Wagoneer': 'Full-size luxury SUV reviving an American classic.',
  'Jeep Wagoneer': 'Premium three-row SUV competing with luxury brands.',
  
  // Hyundai/Kia/Genesis
  'Hyundai Tucson': 'Stunning design and value that redefined compact SUVs.',
  'Hyundai Santa Fe': 'Family SUV with striking looks and outstanding warranty.',
  'Hyundai Palisade': 'Three-row SUV punching well above its price class.',
  'Hyundai Ioniq 5': 'Retro-futuristic EV with 800V ultra-fast charging.',
  'Hyundai Ioniq 6': 'Aerodynamic electric sedan with over 360 miles of range.',
  'Hyundai Kona': 'Subcompact SUV with big personality and available EV option.',
  'Hyundai Elantra': 'Dramatic styling bringing excitement to compact sedans.',
  'Hyundai Sonata': 'Family sedan with cutting-edge design and tech.',
  'Kia Telluride': 'World Car of the Year 2020, exceptional value in three-row SUVs.',
  'Kia Sportage': 'Bold design leadership in the compact SUV segment.',
  'Kia EV6': 'Award-winning electric crossover with genuine performance credibility.',
  'Kia EV9': 'Three-row electric SUV that can charge from 10-80% in 24 minutes.',
  'Kia Sorento': 'Versatile mid-size SUV available as a plug-in hybrid.',
  'Kia Carnival': 'Minivan trying not to look like one, with SUV styling cues.',
  'Kia K5': 'Sporty sedan formerly known as Optima, with available AWD.',
  'Kia Stinger': 'Rear-drive sports sedan that surprised the entire industry.',
  'Genesis G70': 'Compact luxury sedan challenging BMW 3 Series directly.',
  'Genesis G80': 'Executive sedan with stunning design and exceptional value.',
  'Genesis G90': 'Flagship luxury sedan at half the price of German rivals.',
  'Genesis GV70': 'Compact luxury SUV with bold styling and standard features.',
  'Genesis GV80': 'Luxury SUV that announced Genesis as a serious player.',
  'Genesis GV60': 'Electric crossover with advanced technology and face recognition.',
  
  // Subaru
  'Subaru Outback': 'The original lifted wagon, defining the outdoorsy lifestyle.',
  'Subaru Forester': 'Practical AWD crossover beloved by adventurers.',
  'Subaru Crosstrek': 'Small crossover with big capability and cult following.',
  'Subaru WRX': 'Rally-bred performance sedan for driving enthusiasts.',
  'Subaru Impreza': 'Affordable AWD for those who need all-weather confidence.',
  'Subaru Ascent': 'Three-row family SUV with standard AWD.',
  'Subaru BRZ': 'Rear-drive sports car developed with Toyota, pure driving joy.',
  'Subaru Solterra': 'Subaru\'s first electric SUV, developed with Toyota.',
  
  // Mazda
  'Mazda3': 'Premium feel at mainstream prices, best-driving compact car.',
  'Mazda CX-5': 'Upscale compact SUV that handles like a sports sedan.',
  'Mazda CX-30': 'Stylish subcompact crossover with Mazda\'s signature driving feel.',
  'Mazda CX-50': 'Rugged-look crossover for outdoor adventure seekers.',
  'Mazda CX-90': 'Three-row flagship with inline-6 power and rear-wheel-drive platform.',
  'Mazda MX-5 Miata': 'The best-selling roadster of all time, pure driving joy since 1989.',
  
  // Nissan/Infiniti
  'Nissan Altima': 'Mid-size sedan with available AWD, uncommon in its class.',
  'Nissan Rogue': 'Best-selling Nissan with exceptional interior space.',
  'Nissan Pathfinder': 'Three-row SUV returning to its adventure roots.',
  'Nissan Frontier': 'Mid-size truck with bold styling and proven reliability.',
  'Nissan Titan': 'Full-size truck with standard V8 power.',
  'Nissan Z': 'Legendary sports car lineage dating back to the 1970 240Z.',
  'Nissan Ariya': 'Modern electric SUV showcasing Nissan\'s EV expertise.',
  'Nissan Leaf': 'The EV that started it all, first mass-market electric car.',
  'Infiniti Q50': 'Sport sedan with available twin-turbo V6 power.',
  'Infiniti Q60': 'Stylish coupe with up to 400 horsepower.',
  'Infiniti QX50': 'Compact luxury SUV with innovative variable compression engine.',
  'Infiniti QX60': 'Three-row luxury crossover focused on family comfort.',
  'Infiniti QX80': 'Full-size luxury SUV with bold presence.',
  
  // Others
  'Volkswagen ID.4': 'VW\'s mainstream electric SUV with excellent value.',
  'Volkswagen Tiguan': 'Compact SUV with available third row.',
  'Volkswagen Atlas': 'Three-row SUV built for American families.',
  'Volkswagen Golf GTI': 'The hot hatch benchmark for over 45 years.',
  'Volkswagen Golf R': 'All-wheel drive performance hatch with rally heritage.',
  'Volvo XC90': 'Safest luxury SUV, Swedish design excellence.',
  'Volvo XC60': 'Compact luxury SUV with world-class safety.',
  'Volvo XC40': 'Urban SUV with Scandinavian minimalist design.',
  'Volvo S60': 'Sport sedan with available Polestar Engineered performance.',
  'Volvo EX90': 'All-electric three-row SUV with advanced safety tech.',
  'Rivian R1T': 'The electric adventure truck with innovative Camp Kitchen.',
  'Rivian R1S': 'Electric SUV version of the R1T for families.',
  'Lucid Air': 'The most efficient EV ever made, with 500+ mile range.',
  'Dodge Charger': 'Four-door muscle car, one of the last V8 sedans.',
  'Dodge Challenger': 'Retro muscle car keeping the V8 dream alive.',
  'Dodge Durango': 'Three-row SUV with available Hellcat power.',
  'Dodge Hornet': 'Compact performance SUV marking Dodge\'s electrified future.',
  'Ram 1500': 'Full-size truck known for smooth ride and luxurious interior.',
  'Ram 2500': 'Heavy-duty truck for serious work.',
  'Ram 3500': 'Maximum capability for the heaviest towing needs.',
  'GMC Sierra': 'Premium full-size truck with exclusive MultiPro tailgate.',
  'GMC Yukon': 'Full-size SUV with GMC\'s professional-grade features.',
  'GMC Acadia': 'Three-row crossover offering value and versatility.',
  'GMC Terrain': 'Compact SUV with bold styling.',
  'GMC Hummer EV': 'Electric supertruck with 1,000 horsepower and CrabWalk.',
  'Cadillac Escalade': 'The original luxury SUV icon, defining American opulence.',
  'Cadillac CT5': 'Rear-drive luxury sedan with available supercharged V8.',
  'Cadillac Lyriq': 'Cadillac\'s electric future, elegant SUV design.',
  'Cadillac XT5': 'Compact luxury crossover, Cadillac\'s best-seller.',
  'Cadillac XT6': 'Three-row luxury SUV for families.',
  'Lincoln Navigator': 'Full-size luxury SUV competing with Escalade.',
  'Lincoln Aviator': 'Mid-size luxury SUV with available plug-in hybrid.',
  'Lincoln Nautilus': 'Compact luxury crossover with serene interior.',
  'Lincoln Corsair': 'Entry luxury SUV with surprising refinement.',
  'Acura MDX': 'Three-row luxury SUV with genuine performance.',
  'Acura RDX': 'Compact luxury SUV with sporty handling.',
  'Acura TLX': 'Sport sedan with available Type S performance.',
  'Acura Integra': 'Revived nameplate bringing back enthusiast spirit.',
  'Acura ZDX': 'Electric luxury SUV built on GM Ultium platform.',
  'Alfa Romeo Giulia': 'Italian passion in sedan form, genuine driving emotion.',
  'Alfa Romeo Stelvio': 'SUV with sports car handling, named after a famous mountain pass.',
  'Alfa Romeo Tonale': 'Compact plug-in hybrid SUV with Italian style.',
  'Land Rover Range Rover': 'The original luxury SUV, defining the category since 1970.',
  'Land Rover Range Rover Sport': 'Performance-focused Range Rover.',
  'Land Rover Defender': 'Reborn off-road icon with modern luxury.',
  'Land Rover Discovery': 'Versatile family SUV with legendary capability.',
  'Jaguar F-Pace': 'Sports car brand\'s SUV with genuine performance feel.',
  'Jaguar F-Type': 'British sports car with stunning design and sound.',
  'Maserati Grecale': 'Italian luxury SUV bringing Maserati to new buyers.',
  'Maserati Levante': 'First Maserati SUV, exotic Italian styling.',
  'Maserati Ghibli': 'Entry Maserati sedan with exotic appeal.',
  'Maserati Quattroporte': 'Four-door grand tourer, Italian executive luxury.',
  'Maserati MC20': 'Mid-engine supercar marking Maserati\'s performance return.',
  'Lotus Eletre': 'Electric hyper-SUV from the legendary sports car maker.',
  'Lotus Emira': 'Last combustion Lotus, pure driving experience.',
  'Polestar 2': 'Electric performance sedan from Volvo\'s performance brand.',
  'Polestar 3': 'Luxury electric SUV with Scandinavian design.',
  'Mini Cooper': 'The original small car, British charm since 1959.',
  'Mini Countryman': 'Larger Mini with available AWD for adventure.',
  'Mitsubishi Outlander': 'Three-row SUV with available plug-in hybrid.',
  'Mitsubishi Eclipse Cross': 'Compact SUV reviving a sports car nameplate.',
  'Buick Enclave': 'Three-row luxury crossover with whisper-quiet cabin.',
  'Buick Encore GX': 'Subcompact luxury SUV with premium features.',
  'Buick Envision': 'Compact luxury SUV with excellent value.',
  'Chrysler Pacifica': 'The only plug-in hybrid minivan, family innovation.',
  'Chrysler 300': 'Rear-drive sedan with bold American style.',
};

// Get vehicle heritage description, with fallback
export function getVehicleHeritage(vehicleName: string): string {
  return vehicleHeritage[vehicleName] || '';
}
